name: PCC Notification

on:
  push:
    paths:
      - 'docs/data.json'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: |
          curl -d "PCC Tracker-এ পরিবর্তন হয়েছে!" \
          -H "Title: PCC আপডেট!" \
          -H "Priority: urgent" \
          -H "Tags: bell" \
          -H "Click: intent:#Intent;package=com.pcctracker.app;end" \
          ntfy.sh/pcc_tracker_tonmoy